name: Prevent Merge if Workflow Running on Main

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  prevent-concurrent-merge:
    name: Check if Workflow Running on Main
    runs-on: ubuntu-latest

    steps:
      - name: Check for running workflows on main
        run: |
          echo "Checking if any workflow is running on 'main'..."
          running=$(gh run list -R ${{ github.repository }} --json status,headBranch \
            --jq '[.[] | select(.headBranch == "main" and .status == "in_progress")] | length')

          echo "Active runs: $running"
          if [ "$running" -ne 0 ]; then
            echo "❌ A workflow is already running on 'main'. Blocking this merge."
            exit 1
          else
            echo "✅ No workflow running. Proceeding."
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
